services:
  - type: web
    name: equilibrium-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGODB_URI
        scope: build,runtime
        value: ""
      - key: JWT_SECRET
        scope: build,runtime
        value: ""
      - key: PORT
        scope: build,runtime
        value: "4000"
      - key: CLIENT_URL
        scope: build,runtime
        value: ""
